# Generated by Django 5.2.5 on 2026-01-13 17:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('adhaar_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('blood_group', models.CharField(max_length=5)),
                ('category', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=200)),
                ('board_name', models.CharField(max_length=100)),
                ('college_roll_no', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('eleventh_year', models.CharField(max_length=10)),
                ('twelfth_year', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=100)),
                ('enrolled_for', models.CharField(max_length=100)),
                ('sams_login_id', models.CharField(blank=True, max_length=100)),
                ('sams_password', models.CharField(blank=True, max_length=100)),
                ('pen_number', models.CharField(blank=True, max_length=100)),
                ('apaar_id', models.CharField(blank=True, max_length=100)),
                ('visitor1_name', models.CharField(blank=True, max_length=100)),
                ('visitor1_relation', models.CharField(blank=True, max_length=100)),
                ('visitor1_contact', models.CharField(blank=True, max_length=15)),
                ('visitor2_name', models.CharField(blank=True, max_length=100)),
                ('visitor2_relation', models.CharField(blank=True, max_length=100)),
                ('visitor2_contact', models.CharField(blank=True, max_length=15)),
                ('hostel_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('academics_accommodation', models.TextField(blank=True)),
                ('admitted_college_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('college_dress', models.CharField(blank=True, max_length=100)),
                ('books', models.CharField(blank=True, max_length=100)),
                ('college_transportation', models.CharField(blank=True, max_length=100)),
                ('tms_dress', models.CharField(blank=True, max_length=100)),
                ('installment1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('installment2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('installment3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('installment4', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('installment5', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('installment6', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tms_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('guardian_signature', models.CharField(blank=True, max_length=100)),
                ('student_signature', models.CharField(blank=True, max_length=100)),
                ('tms_signature', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('student', 'Student')], default='student', max_length=10)),
                ('store_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
