# Generated by Django 5.2.5 on 2026-01-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_admission_submitted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='store_name',
        ),
    ]
