# Generated by Django 5.2.5 on 2026-01-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_remove_customuser_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='student_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_images/', verbose_name='Student Photo'),
        ),
    ]
