# Generated by Django 5.2.5 on 2026-01-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_admission_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admission_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Admission ID'),
        ),
    ]
