# Generated by Django 6.0.1 on 2026-01-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_expense_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('tuition', 'Tuition Fee'), ('food', 'Fooding'), ('hostel', 'Hostel Fee'), ('transport', 'Transportation'), ('library', 'Library'), ('other', 'Other')], max_length=50),
        ),
    ]
