# Generated by Django 6.0.1 on 2026-01-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_alter_payment_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Organization Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/', verbose_name='Logo')),
                ('address', models.TextField(verbose_name='Address')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('registration_number', models.CharField(max_length=100, unique=True, verbose_name='Registration Number')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Registration Date')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Contact Person')),
                ('organization_type', models.CharField(blank=True, max_length=100, verbose_name='Organization Type')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
    ]
