# Generated by Django 6.0.1 on 2026-02-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0008_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uid',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
