# Generated by Django 6.0.1 on 2026-02-06 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0009_alter_customuser_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='admitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admission',
            name='is_admitted',
            field=models.BooleanField(default=False, verbose_name='Admitted'),
        ),
    ]
