# Generated by Django 6.0.1 on 2026-02-16 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0011_alter_admission_admitted_college_fees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('stream', models.CharField(choices=[('science', 'Science'), ('commerce', 'Commerce'), ('arts', 'Arts')], default='science', max_length=20)),
                ('year', models.CharField(choices=[('11th', '11th Class'), ('12th', '12th Class')], default='11th', max_length=10)),
                ('max_marks', models.IntegerField(default=100)),
                ('passing_marks', models.IntegerField(default=33)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['year', 'stream', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('weekly', 'Weekly Test'), ('monthly', 'Monthly Test'), ('quarterly', 'Quarterly Exam'), ('half_yearly', 'Half Yearly Exam'), ('annual', 'Annual Exam'), ('pre_board', 'Pre-Board Exam'), ('other', 'Other')], default='monthly', max_length=20)),
                ('session', models.CharField(choices=[('morning', 'Morning Session (8 AM - 11 AM)'), ('afternoon', 'Afternoon Session (12 PM - 3 PM)'), ('evening', 'Evening Session (4 PM - 7 PM)')], default='morning', max_length=20)),
                ('batch', models.CharField(help_text='Batch year (e.g., 2024-2025)', max_length=50)),
                ('stream', models.CharField(choices=[('science', 'Science'), ('commerce', 'Commerce'), ('arts', 'Arts')], default='science', max_length=20)),
                ('year', models.CharField(choices=[('11th', '11th Class'), ('12th', '12th Class')], default='11th', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(blank=True, related_name='exams', to='institute.subject')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_marks', models.IntegerField(default=100)),
                ('passing_marks', models.IntegerField(default=33)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('invigilator', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='institute.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.subject')),
            ],
            options={
                'ordering': ['exam_date', 'start_time'],
                'unique_together': {('exam', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ExamAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='institute.exam')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attendance', to='institute.admission')),
            ],
            options={
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_absent', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='institute.examschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='institute.admission')),
            ],
            options={
                'ordering': ['schedule__exam_date', 'student__student_name'],
                'unique_together': {('schedule', 'student')},
            },
        ),
    ]
