# Generated by Django 6.0.1 on 2026-02-17 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0012_subject_exam_examschedule_examattendance_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subjects',
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-exam_date']},
        ),
        migrations.AlterModelOptions(
            name='studentresult',
            options={'ordering': ['exam__exam_date', 'student__student_name']},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='start_date',
        ),
        
        # FIXED: Move AlterUniqueTogether for studentresult AFTER adding exam field
        # Remove this from here and add it later
        
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        # FIXED: This is now correct - DateField, not ForeignKey
        migrations.AddField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='invigilator',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='passing_marks',
            field=models.IntegerField(default=33),
        ),
        migrations.AddField(
            model_name='exam',
            name='room_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.CharField(choices=[('physics_11', 'Physics (11th Science)'), ('chemistry_11', 'Chemistry (11th Science)'), ('mathematics_11', 'Mathematics (11th Science)'), ('biology_11', 'Biology (11th Science)'), ('english_11', 'English (11th Science)'), ('physics_12', 'Physics (12th Science)'), ('chemistry_12', 'Chemistry (12th Science)'), ('mathematics_12', 'Mathematics (12th Science)'), ('biology_12', 'Biology (12th Science)'), ('english_12', 'English (12th Science)')], default='physics_11', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
        
        # Add exam field to studentresult FIRST
        migrations.AddField(
            model_name='studentresult',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='institute.exam'),
        ),
        
        # NOW alter unique_together for studentresult
        migrations.AlterUniqueTogether(
            name='studentresult',
            unique_together={('exam', 'student')},
        ),
        
        migrations.AlterField(
            model_name='exam',
            name='stream',
            field=models.CharField(default='science', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.CharField(default='11th', max_length=10),
        ),
        
        # Remove schedule field from studentresult
        migrations.RemoveField(
            model_name='studentresult',
            name='schedule',
        ),
        
        # Delete old models
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='ExamSchedule',
        ),
    ]