# Generated by Django 6.0.1 on 2026-02-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0013_alter_examschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='stream',
            field=models.CharField(choices=[('science', 'Science'), ('commerce', 'Commerce'), ('arts', 'Arts')], default='science', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.CharField(choices=[('11th', '11th Class'), ('12th', '12th Class')], default='11th', max_length=10),
        ),
    ]
