# Generated by Django 6.0.1 on 2026-02-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0014_alter_exam_stream_alter_exam_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='installment1',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='installment2',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='installment3',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='installment4',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='installment5',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='installment6',
        ),
        migrations.AddField(
            model_name='admission',
            name='subject1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='subject2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='subject3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='subject4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='subject5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='subject6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
