# Generated by Django 6.0.1 on 2026-02-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0015_remove_admission_installment1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='subject1',
            field=models.CharField(blank=True, default='Odia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='subject2',
            field=models.CharField(blank=True, default='English', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='subject3',
            field=models.CharField(blank=True, default='Mathematics', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='subject4',
            field=models.CharField(blank=True, default='Physics', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='subject5',
            field=models.CharField(blank=True, default='Chemistry', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='subject6',
            field=models.CharField(blank=True, choices=[('Information Technology', 'Information Technology'), ('Electronics', 'Electronics'), ('Biology', 'Biology')], max_length=100, null=True),
        ),
    ]
