# Generated by Django 6.0.1 on 2026-02-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0016_alter_admission_subject1_alter_admission_subject2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='subject6',
            field=models.CharField(blank=True, choices=[('Information Technology', 'Information Technology'), ('Electronics', 'Electronics'), ('Biology', 'Biology')], default='Biology', max_length=100, null=True),
        ),
    ]
