# Generated by Django 6.0.1 on 2026-02-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0018_alter_exam_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(choices=[('odia_11', 'Odia (11th Science)'), ('english_11', 'English (11th Science)'), ('physics_11', 'Physics (11th Science)'), ('chemistry_11', 'Chemistry (11th Science)'), ('mathematics_11', 'Mathematics (11th Science)'), ('biology_11', 'Biology (11th Science)'), ('IT_11', 'Information Technology (11th Science)'), ('electronics_11', 'Electronics (11th Science)'), ('odia_12', 'Odia (12th Science)'), ('english_12', 'English (12th Science)'), ('physics_12', 'Physics (12th Science)'), ('chemistry_12', 'Chemistry (12th Science)'), ('mathematics_12', 'Mathematics (12th Science)'), ('biology_12', 'Biology (12th Science)'), ('IT_12', 'Information Technology (12th Science)'), ('electronics_12', 'Electronics (12th Science)')], default='physics_11', max_length=20),
        ),
    ]
